### ISSUE TITLE
Pikmin attack modded invincible enemies or passives, sometimes resulting in the Pikmin stuck following it until one or the other dies

### ISSUE THREAD

**Issue by yumm-dev** [NoteBoxz/LethalMin#10]
Most noticeable with the Surfaced mod installed, the Pikmin will go after entities that are either invincible, passive, or both. The most prominent ones are Horseshoot Crab and the Clown Horn Fish, which the Pikmin will chase and attempt to attack despite them being passives (with the former also being invincible). The Horseshoot Crab is especially a problem as the Pikmin can never get into attacking range of them, but they continue to chase them anyways, resulting in an infinite loop only stoppable by death. I'm no Unity modder, but I'd imagine that creating a blacklist for pikmin targeting certain mobs (adjustable in the config) would do some good and have the issue be resolved.

**Comment by NoteBoxz** [comment]
There is a blacklist in the configs 
![image](https://github.com/user-attachments/assets/40c2e8e6-2312-424f-a5d0-be561c6ba52e)
