### ISSUE TITLE
Pikmin carrying bodies in mines

### ISSUE THREAD

**Issue by Judosii** [NoteBoxz/LethalMin#16]
When in a mine, if a pikmin tries to carry a body out of the mine via the main entrance, they'll stay next to the elevator while carrying the body, and not do anything else. it could be remedied by forcing to use a fire exit.

**Comment by NoteBoxz** [comment]
There is a config option that allows you to force Pikmin to go to fire exits. Use LethalConfig to do toggle this setting during gameplay.
![image](https://github.com/user-attachments/assets/9ed82a30-d7ca-4eb8-9988-66ad7f5625c5)
