### ISSUE TITLE
Pikmin diapering

### ISSUE THREAD

**Issue by eggganing** [NoteBoxz/LethalMin#18]
When i pluck them they just disappear. I cant see them and throw them.

**Comment by NoteBoxz** [comment]
Are there 100 Pikmin spawned in?
This can happen when you have 100 Pikmin out.

**Comment by eggganing** [comment]
Yes

**Comment by NoteBoxz** [comment]
Then this is not an issue, it's just they way the mod works. By default, if a Pikmin is plucked when there are 100 Pikmin already out, it will either automatically be sent to the onion or be removed if they don't have an onion. You can change the maximum amount of Pikmin that can be out at a time though 

![image](https://github.com/user-attachments/assets/60b759d6-56be-41c7-9569-a76875ccffdb)

**Comment by eggganing** [comment]
or i think so cus it just happens to 1 random person in the lobby when they
don't have 100 out nor has anything changed tho.i pluck them then they just
vanish.cant see them cant use them can't do anything.

**Comment by eggganing** [comment]
So i think it is just a bug to do something to with [image: image.png]

**Comment by eggganing** [comment]
You can bug test this mod pack ( too see my point I couldent get it when i
did it as a standalone mod) 0193ad8e-468e-dce9-9627-3237a9238ae9
