### ISSUE TITLE
Onion option

### ISSUE THREAD

**Issue by Fellow9000** [NoteBoxz/LethalMin#19]
I disabled the config option for the onion not to produce sprouts, and the Pikmin left the bodies under the beam. Could the onion still take the bodies and still convert them into Pikmin without creating sprouts and adding them to the count, or is that option meant for something else?

**Comment by NoteBoxz** [comment]
I forgot to make it so Pikmin take things back to the ship instead of the onion when the config is turned off. I'll fix this in the next version

**Comment by NoteBoxz** [comment]
0.2.13
