### ISSUE TITLE
custom moons don't load with LethalMin installed

### ISSUE THREAD

**Issue by GalacticTater** [NoteBoxz/LethalMin#3]
other than the host being the only one being able to control Pikmin, the mod works well! Until custom moons...I tried Aquatis and the moon would not load and was stuck on "Waiting for players". Can try with other moons but thought would post here because this mod is super impressive and would love to see it being able to be used fully! Great job

**Comment by NoteBoxz** [comment]
Usually, glitches like this occur due to an error, could you show me what the console logs when you attempt to load a custom moon?

**Comment by NoteBoxz** [comment]
Fixed it
