### ISSUE TITLE
Extremely laggy while pikmin are carrying objects

### ISSUE THREAD

**Issue by BetaSigmaOmega** [NoteBoxz/LethalMin#4]
I've tested it on a few moons, the level of lag varies heavily, but even just having 10 pikmin carry objects makes the game unplayable. Seems to be much worse while you are physically near the pikmin, but this is not always case, especially while outside.

Only mods active are this mod, Imperium (to test things), and their dependencies.

https://github.com/user-attachments/assets/88f38ae2-317b-49b6-9890-c8c553aa411d

**Comment by NoteBoxz** [comment]
It's imperium, Imperium cannot handle large numbers of entities. I'm not fully sure if that is an issue with mainly imperium, or it has something to do with LethalMin aswell. Imperium seems to lag really badly when too many pikmin start carrying items.
