### ISSUE TITLE
Lag spikes while moving with large number of pikmin followers

### ISSUE THREAD

**Issue by BetaSigmaOmega** [NoteBoxz/LethalMin#5]
Basically title, recorded under the same circumstances as my previous issue. Not completely game-breaking, plus under normal circumstances you likely wouldn't get this many pikmin, but is still pretty bad.

Only mods active are this mod, Imperium (to test things), and their dependencies.

https://github.com/user-attachments/assets/129a053b-1f56-499b-81a5-ff678c3e68a7

**Comment by NoteBoxz** [comment]
It's imperium, Imperium cannot handle large numbers of entities. I'm not fully sure if that is an issue with mainly imperium, or it has something to do with LethalMin aswell.
