### ISSUE TITLE
[bug] Hotkeys not functional in latest 3 versions.

### ISSUE THREAD

**Issue by DravenXD** [NoteBoxz/LethalMin#6]
Hotkey rebinds have not been working since 3 updates or so ago. They are ignored and the game will use defaults regardless of what is set. I see the changelog references a potential "fix" to pikmin not getting thrown, this may be related to hotkeys not functioning. My hotkeys worked before the last three updates. 
They are:
Throw Action = <Keyboard>/z
Switch Forward = <Keyboard>/rightArrow
Switch Backwards = <Keyboard>/leftArrow

**Comment by DravenXD** [comment]
Looks like github removed the parts that used greater than or less than signs in the text, so I'll rewrite the binds using square brackets instead lmao.
Throw Action = [Keyboard]/z
Switch Forward = [Keyboard]/rightArrow
Switch Backwards = [Keyboard]/leftArrow

Btw, tested with a friend. Can confirm on both ends.

**Comment by NoteBoxz** [comment]
Do you have input utils installed? Because the latest versions have Input Utils support for key binds and if you have InputUtils installed then the config key binds won't do anything.

**Comment by DravenXD** [comment]
Disabling inputUtils resolves the issue. But then why did the hotkeys work several versions ago, and why doesn't it conflict with other mods that similarly have custom keybinds in a config like 3rdPerson by verity?

**Comment by NoteBoxz** [comment]
Like I said, when InputUtils is installed, you need to change the keybinds using InputUtils. The Config keybinds don't work.

**Comment by DravenXD** [comment]
I read your message wrong. Thank you very much for your help 👍
