### ISSUE TITLE
Some plucked pikmin are not visible to lower end device users

### ISSUE THREAD

**Issue by ruwubyy** [NoteBoxz/LethalMin#7]
Me and a friend were playing with the mod, and came across an issue where some plucked pikmin were invisible, they were still there and could interact with them, but they couldn't see them.
And this only happen half the time, sometimes the plucked pikmin would be visible, sometimes it wouldn't.
But all idle pikmin (purple, white and bulbmin) were 100% visible, all the time.

**Comment by NoteBoxz** [comment]
I'll look into it.

**Comment by ruwubyy** [comment]
my friend just told me that every pikmin they plucked is 100% visible in single player, so it might be a multiplayer issue

**Comment by NoteBoxz** [comment]
V 0.1.11
